name: Run sqlok tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]

    steps:
      - uses: actions/checkout@v4
      - name: Install postgres
        run: |
          sudo atp update
          sudo apt install postgresql postgresql-contrib
          sudo systemctl status postgresql
          sudo systemclt start postgresql
          psql postgresql://postgres:postgres@localhost:5432/postgres -c "SELECT 1"
          psql service=postgres -c "SELECT 1"
          psql -c "SELECT 1"
        env:
          PGSERVICE: postgres
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Run go unit tests
        run: |
          make test
