name: Run sqlok tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]

    steps:
      - uses: actions/checkout@v4
      - uses: ikalnytskyi/action-setup-postgres@v7
      - name: Install postgres
        env:
          PGSQL_SQLOK_PASSWORD: ${{ secrets.PGSQL_SQLOK_PASSWORD }}
          PGSERVICE: postgres
        run: |
          psql postgresql://postgres:postgres@localhost:5432/postgres -f ./scripts/postgres/roles.sql
          psql postgresql://postgres:postgres@localhost:5432/postgres -f ./scripts/postgres/database.sql
          psql "postgresql://sqlok:$PGSQL_SQLOK_PASSWORD@localhost:5432/sqlok" -c "SELECT 1"
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Run go unit tests
        run: |
          make test
